---
  - name: Create data directory
    file:
      path: "{{  data_dir  }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: Create kms data directory
    file:
      path: "{{  data_dir_kms  }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    become: yes

